server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: order-service
        predicates:
        - Path=/order/**
        filters:
        - StripPrefix=false
        uri: localhost:8091

