server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: order-service
        predicates:
        - Path=/order/**
        uri: localhost:8091
        filters:
        - StripPrefix=false

eureka:
  client:
#     fetchRegistry:true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true

# disable timeout setting
hystrix.command.default.execution.timeout.enabled=false
