server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: order-service
        predicates:
        - Path=/order/**
        uri: lb://ORDER-SERVICE
        filters:
        - StripPrefix=0

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# disable timeout setting
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
