server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: axon-customer
        predicates:
        - Path=/customer/**
        filters:
        - StripPrefix=false
      - id: axon-query
        predicates:
        - Path=/query/**
        filters:
        - StripPrefix=false
      - id: axon-webui
        predicates:
        - Path=/ui/**
        filters:
        - StripPrefix=false

eureka:
  client:
    fetchRegistry:true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
